set(CMAKE_SYSTEM_NAME Generic)

if(WIN32)
    set(EXE_EXTENSION ".exe")
else()
    set(EXE_EXTENSION "")
endif()

set(CMAKE_C_COMPILER gcc${EXE_EXTENSION})
set(CMAKE_CXX_COMPILER g++${EXE_EXTENSION})

if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Debug)
endif()

set(CMAKE_OBJCOPY objcopy${EXE_EXTENSION} CACHE INTERNAL "")
set(CMAKE_RANLIB ranlib${EXE_EXTENSION} CACHE INTERNAL "")
set(CMAKE_SIZE_UTIL size${EXE_EXTENSION} CACHE INTERNAL "")
set(CMAKE_STRIP strip${EXE_EXTENSION} CACHE INTERNAL "")
set(CMAKE_AR ar${EXE_EXTENSION})
set(CMAKE_ASM_COMPILER g++${EXE_EXTENSION})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

set(CMAKE_FIND_ROOT_PATH_LIBRARY ONLY)

set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)