name: Build_tests
on:
  workflow_call:
    inputs:
      preset:
        required: true
        type: string
      app:
        required: true
        type: string

jobs:
  Build_tests:
    runs-on: ubuntu-20.04
    container:
      image: docker/pawelekg95/images/calgopp_x86_64
      credentials:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          BUILD_DIR="/tmp/${{ inputs.app }}-${{ github.sha }}"
          rm -rf "${BUILD_DIR}"
          mkdir "${BUILD_DIR}"
          cd "${BUILD_DIR}"
          cmake ${{ github.workspace }} --preset ${{ inputs.preset }}
          make -j 2
