name: Build tests
on:
  workflow_call:
    inputs:
      preset:
        required: true
        type: string

jobs:
  Build_tests:
    runs-on: self-hosted
    steps:
      - run: |
          BUILD_DIR="/tmp/${{ github.job }}-${{ github.sha }}"
          mkdir "${BUILD_DIR}"
          cd "${BUILD_DIR}"
          cmake ${{ github.workspace }} --preset ${{ inputs.preset }}
          make -j 2
