name: Build tests
on: [push]

jobs:
  Build_calgopp_tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd ${{ github.workspace }}
          mkdir ./cmake-build
          cd ./cmake-build
          cmake .. --preset signal_tests
          make -j 2
      - uses: actions/upload-artifact@v3
        with:
          name: calgopp_tests
          path: ${{ github.workspace }}/cmake-build/bin/tests
