name: Build tests
on: [push]

jobs:
  Build_tests:
    inputs:
      preset:
        required: true
        type: string
      app:
        required: true
        type: string
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          BUILD_DIR="/tmp/${{ inputs.app }}-${{ github.sha }}"
          mkdir "${BUILD_DIR}"
          cd "${BUILD_DIR}"
          cmake ${{ github.workspace }} --preset ${{ inputs.preset }}
          make -j 2

  Build_signal_tests_gcc_debug:
    name: Build_signal_tests_gcc_debug
    uses: Build_tests
      with:
        preset: signal_tests_gcc_debug
        app: Build_signal_tests_gcc_debug

  Build_signal_tests_gcc_release:
    name: Build_signal_tests_gcc_release
    uses: Build_tests
    with:
      preset: signal_tests_gcc_release
      app: Build_signal_tests_gcc_release

  Build_signal_tests_clang_debug:
    name: Build_signal_tests_clang_debug
    uses: Build_tests
    with:
      preset: signal_tests_clang_debug
      app: Build_signal_tests_clang_debug

  Build_signal_tests_clang_release:
    name: Build_signal_tests_clang_release
    uses: Build_tests
    with:
      preset: signal_tests_clang_release
      app: Build_signal_tests_clang_release
