name: Calgopp_CI
on: push

jobs:
  # Environment
  Calgopp_x86_64_docker:
    name: Calgopp_x86_64_docker
    uses: ./.github/workflows/environment.yml
    with:
      image: calgopp_x86_64
    secrets: inherit

  # Build tests stage
  Build_signal_tests_gcc_debug:
    name: Build_signal_tests_gcc_debug
    needs: Calgopp_x86_64_docker
    uses: ./.github/workflows/build_tests.yml
    with:
      preset: signal_tests_gcc_debug
      app: Build_signal_tests_gcc_debug
    secrets: inherit

  Build_types_tests_gcc_debug:
    name: Build_types_tests_gcc_debug
    needs: Calgopp_x86_64_docker
    uses: ./.github/workflows/build_tests.yml
    with:
      preset: types_tests_gcc_debug
      app: Build_types_tests_gcc_debug
    secrets: inherit

  Build_algorithm_tests_gcc_debug:
    name: Build_algorithm_tests_gcc_debug
    needs: Calgopp_x86_64_docker
    uses: ./.github/workflows/build_tests.yml
    with:
      preset: algorithm_tests_gcc_debug
      app: Build_algorithm_tests_gcc_debug
    secrets: inherit

  Build_math_tests_gcc_debug:
    name: Build_math_tests_gcc_debug
    needs: Calgopp_x86_64_docker
    uses: ./.github/workflows/build_tests.yml
    with:
      preset: math_tests_gcc_debug
      app: Build_math_tests_gcc_debug
    secrets: inherit

  # Test stage
  Signal_test:
    name: Signal_test
    needs: Build_signal_tests_gcc_debug
    uses: ./.github/workflows/test.yml
    with:
      artifacts_name: Build_signal_tests_gcc_debug-${{ github.sha }}
      test_app: bin/tests
      arguments: ~"Signal tests - peaks"
    secrets: inherit

  Types_test:
    name: Types_test
    needs: Build_types_tests_gcc_debug
    uses: ./.github/workflows/test.yml
    with:
      artifacts_name: Build_types_tests_gcc_debug-${{ github.sha }}
      test_app: bin/tests
    secrets: inherit

  Algorithm_test:
    name: Algorithm_test
    needs: Build_algorithm_tests_gcc_debug
    uses: ./.github/workflows/test.yml
    with:
      artifacts_name: Build_algorithm_tests_gcc_debug-${{ github.sha }}
      test_app: bin/tests
    secrets: inherit

  Math_test:
    name: Math_test
    needs: Build_math_tests_gcc_debug
    uses: ./.github/workflows/test.yml
    with:
      artifacts_name: Build_math_tests_gcc_debug-${{ github.sha }}
      test_app: bin/tests
      arguments: ~"Benchmark test"
    secrets: inherit

  # Valgrind tests
  Signal_test_valgrind:
    name: Signal_test_valgrind
    needs: Signal_test
    uses: ./.github/workflows/valgrind.yml
    with:
      artifacts_name: Build_signal_tests_gcc_debug-${{ github.sha }}
      test_app: bin/tests
      arguments: ~"Signal tests - peaks"
    secrets: inherit

  Types_test_valgrind:
    name: Types_test_valgrind
    needs: Types_test
    uses: ./.github/workflows/valgrind.yml
    with:
      artifacts_name: Build_types_tests_gcc_debug-${{ github.sha }}
      test_app: bin/tests
    secrets: inherit

  Algorithm_test_valgrind:
    name: Algorithm_test_valgrind
    needs: Algorithm_test
    uses: ./.github/workflows/valgrind.yml
    with:
      artifacts_name: Build_algorithm_tests_gcc_debug-${{ github.sha }}
      test_app: bin/tests
    secrets: inherit

  Math_test_valgrind:
    name: Math_test_valgrind
    needs: Math_test
    uses: ./.github/workflows/valgrind.yml
    with:
      artifacts_name: Build_math_tests_gcc_debug-${{ github.sha }}
      test_app: bin/tests
      arguments: ~"Benchmark test"
    secrets: inherit

  # Quality
  Clang-format:
    needs: Build_signal_tests_gcc_debug
    uses: ./.github/workflows/quality.yml
    with:
      pre_run: cd "${{ github.workspace }}"
      linter: run-clang-format.py
      arguments: -r lib test
    secrets: inherit

  Clang-tidy:
    needs: Build_signal_tests_gcc_debug
    uses: ./.github/workflows/quality.yml
    with:
      pre_run: cd "${{ github.workspace }}"; rm -rf ./cmake-build; mkdir ./cmake-build; cd ./cmake-build; cmake .. --preset signal_tests_clang_debug
      linter: run-clang-tidy
    secrets: inherit

  Dockerfiles-hadolint:
    needs: Calgopp_x86_64_docker
    uses: ./.github/workflows/quality.yml
    with:
      linter: hadolint
      arguments: .github/*.dockerfile
    secrets: inherit

  Pylint:
    needs: Calgopp_x86_64_docker
    uses: ./.github/workflows/quality.yml
    with:
      linter: pylint
      arguments: utils/sha256.py
    secrets: inherit
