name: Build_documentation_and_deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          BUILD_DIR="/tmp/calgopp-doxygen-${{ github.sha }}"
          rm -rf "${BUILD_DIR}"
          mkdir "${BUILD_DIR}"
          cd "${BUILD_DIR}"
          cmake ${{ github.workspace }} --preset signal_tests_clang_debug
          make doxygen

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: /tmp/calgopp-doxygen-${{ github.sha }}/docs # The folder the action should deploy.
      - run: rm -rf /tmp/calgopp-doxygen-${{ github.sha }}
