name: Prepare_environment
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  Build_image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: pawelekg95/images

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/${{ inputs.image }}.dockerfile
          push: true
          tags: pawelekg95/${{ inputs.image }}:${{ github.sha }}
