name: Prepare_environment
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  Build_image:
    runs-on: ubuntu-20.04
    environment: docker
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        uses: docker/login-action@v1
        with:
          username: ${{ DOCKER_LOGIN }}
          password: ${{ DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/pawelekg95/${{ inputs.image }}:${{ github.sha }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/${{ inputs.image }}.dockerfile
          push: true
