name: Prepare_environment
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  Check_if_exists:
    runs-on: ubuntu-20.04
    environment: docker
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check if image exists
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u ${{ env.DOCKER_LOGIN }} -p ${{ env.DOCKER_PASSWORD }}
          result=0
          docker manifest inspect pawelekg95/${{ inputs.image }} > /dev/null || result=$?
          echo "IMAGE_EXISTS=$result" >> $GITHUB_ENV

  Build_image:
    runs-on: ubuntu-20.04
    needs: Check_if_exists
    environment: docker
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        if: ${{ env.IMAGE_EXISTS == 0 }}
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_LOGIN }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        if: ${{ env.IMAGE_EXISTS == 0 }}
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: pawelekg95/${{ inputs.image }}:latest

      - name: Build and push Docker image
        if: ${{ env.IMAGE_EXISTS == 0 }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/${{ inputs.image }}.dockerfile
          push: true
          tags: pawelekg95/${{ inputs.image }}:latest
