name: Code quality template
on:
  workflow_call:
    inputs:
      module_name:
        required: true
        type: string
      linter:
        required: true
        type: string

jobs:
  Linter:
    runs:
      using: 'docker'
      image: 'calgopp_arm64'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: cd ${{ github.workspace }}
      - run: ${{ inputs.linter }} ${{ inputs.module_name }}
