name: Quality
on:
  workflow_call:
    inputs:
      linter:
        required: true
        type: string
      arguments:
        required: false
        type: string
      pre_run:
        required: false
        type: string
      post_run:
        required: false
        type: string

jobs:
  Quality:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          ${{ inputs.pre_run }}
          ${{ inputs.linter }} ${{ inputs.arguments }}
          ${{ inputs.post_run }}
