name: Quality
on:
  workflow_call:
    inputs:
      linter:
        required: true
        type: string
      arguments:
        required: false
        type: string
      pre_run:
        required: false
        type: string
      post_run:
        required: false
        type: string

jobs:
  Quality:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          eval "${{ inputs.pre_run }}"
          eval "${{ inputs.linter }} ${{ inputs.arguments }}"
          eval "${{ inputs.post_run }}"
