name: Code quality template
on:
  workflow_run:
    workflows: [ "Build tests" ]
    types: [ completed ]

jobs:
  Clang-format:
    uses: ./.github/workflows/quality_template.yml
    with:
      module_name: lib
      linter: python3 ./tools/run-clang-format.py -r
    secrets: inherit

  Clang-tidy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd ${{ github.workspace }}
          mkdir ./cmake-build
          cd ./cmake-build
          cmake .. --preset signal_tests
          python3 ../tools/run-clang-tidy.py

  Valgrind:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          name: calgopp_tests
      - run: valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=123 --fair-sched=yes ./calgopp_tests
