name: Code quality template
on: [push]

jobs:
  Clang-format:
    uses: ./.github/workflows/quality_template.yml
    with:
      module_name: lib
      linter: ./run-clang-format.py -r
    secrets: inherit

  Clang-tidy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: cd ${{ github.workspace }}
      - run: mkdir cmake-build
      - run: cd cmake-build
      - run: cmake --preset signal_tests
      - run: ../tools/run-clang-tidy.py

  Valgrind:
    runs-on: self-hosted
    needs: Build_calgopp_tests
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          name: calgopp_tests
      - run: valgrind ./calgopp_tests
