name: Quality
on: [push]
jobs:
  Clang-format:
    needs: Build_signal_tests_gcc_debug
    runs-on: self-hosted
    steps:
      - uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: 'Build_signal_tests_gcc_debug'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - uses: actions/checkout@v3
      - run: |
          cd ${{ github.workspace }}
          run-clang-format.py -r lib test

  Clang-tidy:
    needs: Build_signal_tests_gcc_debug
    runs-on: self-hosted
    steps:
      - uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: 'Build_signal_tests_gcc_debug'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - uses: actions/checkout@v3
      - run: |
          cd ${{ github.workspace }}
          mkdir ./cmake-build
          cd ./cmake-build
          cmake .. --preset signal_tests_clang_debug
          run-clang-tidy
