name: Quality
on:
  workflow_run:
    workflows: ["Build tests"]
    types: [completed]
    branches:
      - '**'

jobs:
  Clang-format:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd ${{ github.workspace }}
          run-clang-format.py -r lib test

  Clang-tidy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd ${{ github.workspace }}
          mkdir ./cmake-build
          cd ./cmake-build
          cmake .. --preset signal_tests_clang_debug
          run-clang-tidy
