name: Code quality template
on: [push]

jobs:
  Clang-format:
    uses: ./.github/workflows/quality_template.yml
    with:
      module_name: lib
      linter: ./run-clang-format.py -r
    secrets: inherit

  Dockerfiles_Hadolint:
    uses: ./.github/workflows/quality_template.yml
    with:
      module_name: .github/*.dockerfile
      linter: hadolint
    secrets: inherit

  Clang-tidy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: cd ${{ github.workspace }}
      - run: mkdir cmake-build
      - run: cd cmake-build
      - run: cmake --preset signal_tests
      - run: ../tools/run-clang-tidy.py