name: Run tests
on: [push]

jobs:
  Signal_test:
    steps:
      - uses: lewagon/wait-on-check-action@v1.0.0
          with:
            ref: ${{ github.ref }}
            check-name: 'Build_signal_tests_gcc_debug'
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            wait-interval: 10
      - uses: .github/workflows/test_template.yml
        with:
          test_app: /tmp/Build_signal_tests_gcc_debug-${{ github.sha }}/bin/tests

  Valgrind:
    needs: Signal_test
    steps:
      - uses: .github/workflows/test_template.yml
        with:
          test_app: valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=123 --fair-sched=yes /tmp/Build_signal_tests_gcc_debug-${{ github.sha }}/bin/tests
