name: Test
on: [push]
jobs:
  Calgopp_test:
    runs-on: self-hosted
    needs: Build_calgopp_tests
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          name: calgopp_tests
      - run: ./calgopp_tests
