name: Run_tests
on:
  workflow_call:
    inputs:
      test_app:
        required: true
        type: string
      arguments:
        required: false
        type: string
      pre_run:
        required: false
        type: string
      post_run:
        required: false
        type: string

jobs:
  Test:
    runs-on: self-hosted
    steps:
      - run: |
          eval "${{ inputs.pre_run }}"
          eval "${{ inputs.test_app }} ${{ inputs.arguments }}"
          eval "${{ inputs.post_run }}"
