name: Run_tests
on:
  workflow_call:
    inputs:
      test_app:
        required: true
        type: string
      arguments:
        required: false
        type: string
      pre_run:
        required: false
        type: string
      post_run:
        required: false
        type: string

jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          ${{ inputs.pre_run }}
          ${{ inputs.test_app }} ${{ inputs.arguments }}
          ${{ inputs.post_run }}
