name: Valgrind_tests
on:
  workflow_call:
    inputs:
      artifacts_name:
        required: true
        type: string
      test_app:
        required: true
        type: string
      arguments:
        required: false
        type: string
      pre_run:
        required: false
        type: string
      post_run:
        required: false
        type: string

jobs:
  Valgrind_Test:
    runs-on: ubuntu-20.04
    environment: docker
    env:
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    container:
      image: pawelekg95/calgopp_x86_64:latest
      credentials:
        username: ${{ env.DOCKER_LOGIN }}
        password: ${{ env.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifacts_name }}

      - name: Run test application under valgrind
        run: |
          chmod 755 ${{ inputs.test_app }}
          ${{ inputs.pre_run }}
          valgrind --leak-check=full \
                   --show-leak-kinds=all \
                   --error-exitcode=123 \
                   --fair-sched=yes \
                   --track-origins=yes \
                   --suppressions=tools/calgopp.supp \
                   ${{ inputs.test_app }} ${{ inputs.arguments }}
          ${{ inputs.post_run }}
